apiVersion: v1
kind: Service
metadata:
  name: lifebit
  labels:
    app: lifebit
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lifebit
  type: LoadBalancer